version: '3'
services:
  dbadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    ports: 
    - "5555:80"
  identity_db:
    image: postgres:alpine
    restart: always
    env_file: .env
    ports:
    - "5432:5432"